### 5. Test Create Menu
POST http://localhost:5000/api/menu/createMenu
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzU1YzhkNGE3N2QyYWYxZWU4Nzc0MDYiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMzNjc1ODY0LCJleHAiOjE3MzQyODA2NjR9.4X-v3D9zwVY2gZsJoZCf7kGSV_AFD_XfKbpp7uuwVEE

{
  "title": "California Roll",
  "category": "Sushi",
  "price": 12.99,
  "description": "A popular sushi roll with crab, avocado, and cucumber.",
  "imageURL": "https://example.com/images/california_roll.jpg",
  "dietaryFlags": ["gluten-free", "dairy-free"]
}

### 4. Test Get All Menu - Public Route (no authentication required)
### tocken = '9a3fad9ca9b6603d0e27b01a67ec1832a4105560fc5a67c0016fa17758fb00c29a96c0a99b5e013f2c7df9ac8f5afcc16e4fb08d685e67c641ef0e5fec564e8d'
GET http://localhost:5000/api/menu/


### 注册测试
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "john_doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

### 注册 Admin User
POST http://localhost:5000/auth/register
Content-Type: application/json

{
   "username": "admin",
  "email": "admin@example.com",
  "password": "admin123",
  "role": "admin"
}

###

### 登录测试
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

###
### 登录Admin 
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
   "username": "admin",
  "password": "admin123"

}

###
POST http://localhost:5000/api/auth/admin-route
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzU1YzhkNGE3N2QyYWYxZWU4Nzc0MDYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzM2NzY4NDAsImV4cCI6MTczNDI4MTY0MH0.n_5nF5mo-o4t2QEUS8TZI3CCiBpeJdSDIqrW-shFqNY
Content-Type: application/json

### Orders - for each User
GET http://localhost:5000/api/auth/user/menu
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzU2MGNiZDNiOWZlYWRmZjY1OTQ2ZWMiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMzNjk0MTI0LCJleHAiOjE3MzM3ODA1MjR9.PFyqnR9jOl7Uc1RaIEdPXaRceMLmPb8XP65cYwAjEQI

### Delete User (only Admin)
DELETE http://localhost:5000/api/auth/user/675609dd3b9825499e8fabb4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzU2MGNiZDNiOWZlYWRmZjY1OTQ2ZWMiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMzNjk0MTI0LCJleHAiOjE3MzM3ODA1MjR9.PFyqnR9jOl7Uc1RaIEdPXaRceMLmPb8XP65cYwAjEQI


### 
GET http://localhost:5000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzU2MGNiZDNiOWZlYWRmZjY1OTQ2ZWMiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMzNjk0MTI0LCJleHAiOjE3MzM3ODA1MjR9.PFyqnR9jOl7Uc1RaIEdPXaRceMLmPb8XP65cYwAjEQI
